name: 'Zad 2 Workflow'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
     CURRENT_VERSION: ${{ steps.version.outputs.CURRENT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Retrieve app version
        id: version
        run: |
         CURRENT_VERSION=$(sed -nE 's/.*<p>([0-9]+\.[0-9]+\.[0-9]+)<\/p>.*/\1/p' app/index.html)
         echo "CURRENT_VERSION=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"

  dockerCI:
    needs: read-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kkmp13/zad2:${{ needs.read-version.outputs.CURRENT_VERSION }}

  kubernetesCI:
    needs: [read-version, dockerCI]
    runs-on: ubuntu-latest
    outputs:
     CHANGED: ${{ steps.verify_diff.outputs.CHANGED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: kkmp/Config-repo
          token: ${{ secrets.ACTIONS_TOKEN }}
          
      - name: Check if there are any changes
        id: verify_diff
        run: |
          if grep -q "kkmp13/zad2:${{ needs.read-version.outputs.CURRENT_VERSION }}" deployment.yaml; then
            echo "CHANGED=false" >> "$GITHUB_OUTPUT"
          else
            echo "CHANGED=true" >> "$GITHUB_OUTPUT"
          fi;
      
      - name: Commit
        if: steps.verify_diff.outputs.CHANGED == 'true'
        run: |
          git config user.name github-commiter
          git config user.email github-commiter@github.com
          sed -i 's/kkmp13\/zad2:.*/kkmp13\/zad2:${{ needs.read-version.outputs.CURRENT_VERSION }}/g' deployment.yaml
          git add -u
          git commit -m "Update for app version ${{ needs.read-version.outputs.CURRENT_VERSION }}"
          git push -u origin main
          
      - name: No changes
        if: steps.verify_diff.outputs.CHANGED == 'false'
        run: |
          echo "No changes to commit."